=== ensaiosclinicos/clinicaltrials/clinicaltrials/registry/xml/reclac.dtd
<!-- file reclac.dtd

RECLAC: Latin-American and Caribbean Clinical Trial Record XML DTD
DTD Version 1.0: 2010-03-01

This DTD depends on the reclac-vocabularies.mod definitions file.

See:
http://reddes.bvsalud.org/projects/clinical-trials/wiki/RegistrationDataModel

Loosely based on the WHO ICTRP XML DTD, http://www.who.int/ictrp
DTD Version 1.0: 2008-04-23 (with changes up to and including 2008-09-15)

Most element names are the same. Structure is different.
This is intended to represent a single trial record.

Comments:
  - "TRDS n (x..y)": field number in the ICTRP Trial Registration Data Set
                     (x..y) indicate element multiplicity in UML notation
  - "RECLAC": field defined in this DTD but not present in the ICTRP DTD
=========================================================================== -->

<!ENTITY % vocabularies SYSTEM "reclac-vocabularies.mod">
%vocabularies;

<!ELEMENT trial (trial_identification, sponsors_and_support, health_conditions,
		 interventions)> <!--, recruitment, study_type, outcomes, contacts, references+) -->
    <!ATTLIST trial type (interventional) #REQUIRED>
    <!-- trial record must have explicit attribute type="interventional"
         in preparation for eventual support for observational trials -->

    <!ELEMENT trial_identification (scientific_title, scientific_acronym?,
				    public_title?, acronym?, utn?, reclac_id?,
				    secondary_ids*)>

	<!ELEMENT scientific_title (#PCDATA)>                       <!--TRDS 10a (1)-->
	<!ELEMENT scientific_acronym (#PCDATA)>                     <!--TRDS 10b (0..1)-->
	<!ELEMENT public_title (#PCDATA)>                           <!--TRDS 9a (0..1)-->
	<!ELEMENT acronym (#PCDATA)>                                <!--TRDS 9b (0..1)-->
	<!ELEMENT utn (#PCDATA)>                                    <!--TRDS 3 (0..1)-->
	<!ELEMENT reclac_id (#PCDATA)>                              <!--TRDS 1 (0..1)-->
	<!ELEMENT secondary_ids (secondary_id+)>
	    <!ELEMENT secondary_id (sec_id,issuing_authority)>
		<!ELEMENT sec_id (#PCDATA)>                         <!--TRDS 3a (0..*)-->
		<!ELEMENT issuing_authority (#PCDATA)>              <!--TRDS 3b (0..*)-->

	<!ATTLIST scientific_title lang NMTOKEN "en">
	<!ATTLIST scientific_acronym lang NMTOKEN "en">
	<!ATTLIST public_title lang NMTOKEN "en">
	<!ATTLIST acronym lang NMTOKEN "en">

    <!ELEMENT sponsors_and_support (primary_sponsor, secondary_sponsor*, source_support*)>
	<!ELEMENT primary_sponsor (name, address?)>                 <!--TRDS 5 (1)-->
	    <!ATTLIST primary_sponsor
		country (%countrycode.options;) #REQUIRED>
	<!ELEMENT secondary_sponsor (name, address?)>               <!--TRDS 6 (0..*)-->
	    <!ATTLIST secondary_sponsor
		country (%countrycode.options;) #REQUIRED>
	<!ELEMENT source_support (name, address?)>                  <!--TRDS 4 (0..*)-->
	    <!ATTLIST source_support
		country (%countrycode.options;) #REQUIRED>
    	    <!ELEMENT name (#PCDATA)>
	    <!ELEMENT address (#PCDATA)>

    <!ELEMENT health_conditions (freetext?, hc_code*, keyword*)>
        <!ELEMENT freetext (#PCDATA)>                               <!--TRDS 12a, 13a (0..1)-->
        <!ELEMENT hc_code (#PCDATA)>                                <!--TRDS 12b (0..*)-->
	    <!ATTLIST hc_code
		vocabulary (%vocabulary.options;) #REQUIRED
		version CDATA #IMPLIED>
        <!ELEMENT keyword (#PCDATA)>                                <!--TRDS 12c, 13c (0..*)-->
	    <!ATTLIST keyword
		vocabulary (%vocabulary.options;) #REQUIRED
		version CDATA #IMPLIED>

    <!ELEMENT interventions (freetext?, i_code*, keyword*)>           <!--TRDS 12a (0..1)-->
        <!ELEMENT i_code (#PCDATA)>                                   <!--TRDS 12b (0..*)-->
	    <!ATTLIST i_code
		value (%interventioncode.options;) #IMPLIED>

=== ensaiosclinicos/clinicaltrials/clinicaltrials/registry/xml/sample_1a.xml
<!DOCTYPE trial SYSTEM "reclac.dtd">
<!--the simplest possible valid RECLAC trial XML-->
<!--based on data from the ANZCTR; trial: ACTRN12610000133033-->
<trial type="interventional">
    <trial_identification>
      	<!--TRDS 10a (1)-->
        <scientific_title>Tactile and kinesthetic stimulation program during hospitalization and behavioral analysis in preterm neonates</scientific_title>
    </trial_identification>
    <sponsors_and_support>
	<!--TRDS 5 (1)-->
	<primary_sponsor country="BR">
	    <name>Conselho Nacional de Desenvolvimento Cientifico e Tecnologico</name>
	</primary_sponsor>
    </sponsors_and_support>
    <health_conditions>
	<freetext>preterm neonates</freetext>
    </health_conditions>
    <interventions>
    	<i_code value="behavioural" />
    </interventions>
</trial>

=== ensaiosclinicos/clinicaltrials/clinicaltrials/registry/xml/sample_1b.xml
<!DOCTYPE trial SYSTEM "reclac.dtd">
<!--a realistic and valid RECLAC trial XML-->
<!--based on data from the ANZCTR; trial: ACTRN12610000133033-->
<trial type="interventional">
    <trial_identification>
  	<!--TRDS 10a (1)-->
        <scientific_title>Behavioral analysis of preterm neonates included in a tactile and kinesthetic stimulation program during hospitalization in preterm neonates</scientific_title>
	<!--TRDS 10b (0-1)-->
        <scientific_acronym>BATIK</scientific_acronym>
	<!--TRDS 9a (0-1)-->
	<public_title>Tactile and kinesthetic stimulation program during hospitalization and behavioral analysis in preterm neonates</public_title>
	<!--TRDS 9b (0-1)-->
        <acronym>TAKS</acronym>
	<!--TRDS 3a/3b (0-1)-->
	<utn>U9999-9999-0102</utn>
	<!--TRDS 1 (0-1)-->
	<reclac_id>RBR-9zz-2bc</reclac_id>
	<secondary_ids>
	    <secondary_id>
		<!--TRDS 3a (0-N)-->
		<sec_id>ACTRN12610000133033</sec_id>
		<!--TRDS 3b (0-N)-->
		<issuing_authority>ANZCTR</issuing_authority>
	    </secondary_id>
	</secondary_ids>
    </trial_identification>
    <sponsors_and_support>
	<!--TRDS 5 (1)-->
	<primary_sponsor country="BR">
	    <name>Universidade de São Paulo</name>
	    <address>
		Rua Prof. Mello Moraes, 1721
		Cidade Universitaria
		Sao Paulo, SP, CEP 055508-900
	    </address>
	</primary_sponsor>
	<!--TRDS 6 (0..*)-->
	<secondary_sponsor country="BR">
	    <name>Andreia Menandro Ferreira</name>
	    <address>
		Rua Cônego Valadão, 1539, apt 53
		Gopouva,
		Guarulhos, SP, CEP 07040-000
	    </address>
	</secondary_sponsor>
	<!--TRDS 4 (0..*)-->
	<source_support country="BR">
	    <name>Conselho Nacional de Desenvolvimento Cientifico e Tecnologico</name>
	    <address>
		SEPN 507 Ed. CNPq - Terreo - Sala 7
		Brasília, DF, CEP 70740-901
	    </address>
	</source_support>
    </sponsors_and_support>
    <health_conditions>
        <!--TRDS 12a (0..1)-->
	<freetext>preterm neonates</freetext>
        <!--TRDS 12b (0..*)-->
	<hc_code vocabulary="decs" version="2009">M01.060.703.520</hc_code>
        <!--TRDS 12c (0..*)-->
	<keyword vocabulary="decs">C13.703.420.491.500</keyword>
    </health_conditions>
    <interventions>
        <!--TRDS 13a (0..1)-->
	<freetext>
	Stable preterm neonates received tactile and kinesthetic stimulation
	during hospitalization; by trained author and mothers. With ligth
	touch and arms and legs mobilization; during 5 to 15 minutes daily,
	since preterm was clinically stable until hospital discharge.
	</freetext>
        <!--TRDS 13b (0..*)-->
	<i_code value="behavioural" />
        <!--TRDS 13c (0..*)-->
	<keyword vocabulary="decs" version="2009">F02.830.816.850</keyword>
    </interventions>
</trial>
